<Project>
  <PropertyGroup>
    <Authors>Aftab</Authors>
    <Company>Aftab</Company>
    <Copyright>Copyright © 2025 Aftab</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/aftabkh4n/BlazorMemory</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/aftabkh4n/BlazorMemory</PackageProjectUrl>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeSymbols>false</IncludeSymbols>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>blazormemory-icon.png</PackageIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)..\README.md"
          Pack="true"
          PackagePath="\" />
    <None Include="$(MSBuildThisFileDirectory)..\assets\blazormemory-icon.png"
          Pack="true"
          PackagePath="\" />
  </ItemGroup>
</Project>
